version = 0.1
[default.deploy.parameters]
stack_name = "isu-geo-api"
resolve_s3 = true
s3_prefix = "isu-geo-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "DBInstanceIdentifier=\"isu-geo-db\" DBName=\"isu_geo_db\" RDSSecretKey=\"isu-geo-db\""
